config/routes.rb
Rails.application.routes.draw do
  resources :drivers
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_one :license
  accepts_nested_attributes_for :license
end

app/models/license.rb
class License < ActiveRecord::Base
  belongs_to :driver
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

  def index
    @drivers = Driver.all
  end

  def show
    @driver = Driver.find(params[:id])
  end

  def new
    @driver = Driver.new
    @driver.build_license
  end

  def create
    @driver = Driver.new(driver_params)
    if @driver.save
      redirect_to @driver
    else
      render 'new'
    end
  end

  def edit
    @driver = Driver.find(params[:id])
  end

  def update
    @driver = Driver.find(params[:id])
    @driver.update(driver_params)
    if @driver.save
      redirect_to @driver
    else
      render 'edit'
    end
  end

  private

    def driver_params
      params.require(:driver).permit(:fname, :lname, license_attributes: [:number, :state])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for @driver do |f| %>
  <div>
    <%= f.label :firstname, 'First Name' %>
    <%= f.text_field :fname%><br/>
  </div>

  <div>
    <%= f.label :lname, 'Last Name' %>
    <%= f.text_field :lname %><br/>
  </div>

  <%= f.fields_for :license do |lb| %>
    <div>
      <%= lb.label :number, 'Drivers License' %>
      <%= lb.text_field :number %><br/>
    </div>
    <div>
      <%= lb.label :state %>
      <%= lb.text_field :state %><br/>
    </div>
  <% end %>

  <%= f.submit "Creating Driver "%>

<% end %>

app/views/drivers/edit.html.erb
<%= render 'form' %>

app/views/drivers/index.html.erb
<h1>Listing of Drivers</h1>
<ul>
  <% @drivers.each do |driver| %>
    <li>
      <%= driver.fname %> <%= driver.lname %>
      <%= link_to "show", driver_path(driver)%>
    </li>
  <%end%>
  <%= link_to "New Driver", new_driver_path %>
</ul>

app/views/drivers/new.html.erb
<%= render 'form' %>

app/views/drivers/show.html.erb
<p><%= @driver.fname%></p>
<p><%= @driver.lname%></p>
<% if @driver.license.present? %>
  <p><%= @driver.license.number %></p>
  <p><%= @driver.license.state %></p>
<% end %>
<p>
  <%= link_to "Edit", edit_driver_path(@driver) %> | 
  <%= link_to "Destroy", driver_path(@driver), method: :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drivers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>